export default {
  EXCURSION_LIST_REQUEST: 'EXCURSION_LIST_REQUEST',
  EXCURSION_LIST_SUCCESS: 'EXCURSION_LIST_SUCCESS',
  EXCURSION_LIST_FAIL: 'EXCURSION_LIST_FAIL',
  EXCURSION_DETAILS_REQUEST: 'EXCURSION_DETAILS_REQUEST',
  EXCURSION_DETAILS_SUCCESS: 'EXCURSION_DETAILS_SUCCESS',
  EXCURSION_DETAILS_FAIL: 'EXCURSION_DETAILS_FAIL',
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM'
};
